### ISSUE TITLE
Switch only showing from 0-A

### ISSUE THREAD

**Issue by garlik82** [r-salas/ical-videogames#1]
Hi there and thank you for your work.

I noticed the new Zelda game isn't showing on my calendar. 
I noticed the link used only shows games from 0 to A. 
Is this an issue or am I doing something wrong?

Thanks again

**Comment by r-salas** [comment]
Fixed in 8e7506efaca8cb2d806d16be7782000e8a5b936a. Thank you very much for your feedback!
